apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web
---
apiVersion: v1  
kind: Service
metadata:
  name: web-lb
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: web