apiVersion: skaffold/v3
kind: Config
metadata:
  name: k--skaffold
build:
  artifacts:
  - image: thihenos/docker-node
    context: src
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/service.yaml
